// Generated by https://quicktype.io

export interface Results {
    results:      IPlato[];
    offset:       number;
    number:       number;
    totalResults: number;
}

export interface IPlato {
    id:        number;
    title:     string;
    image:     string;
    imageType: ImageType;
}

export enum ImageType {
    Jpg = "jpg",
}
